/*
 * Copyright (c) 2018, hiwepy (https://github.com/hiwepy).
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.apache.shiro.spring.boot.captcha;

import javax.servlet.ServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.apache.shiro.authc.AuthenticationException;
import org.apache.shiro.biz.authc.exception.IncorrectCaptchaException;
import org.apache.shiro.biz.authc.token.CaptchaAuthenticationToken;
import org.apache.shiro.biz.web.filter.authc.captcha.CaptchaResolver;
import org.apache.shiro.web.util.WebUtils;

import java.lang.reflect.Method;

/**
 * A {@link CaptchaResolver} that validates captchas generated by the JCaptcha library.
 * <p>Requires the jcaptcha-spring-boot-starter dependency on the classpath at runtime.</p>
 *
 * @author <a href="https://github.com/loong10k">Loong Wan</a>
 * @since 1.0.0
 */
public class ShiroJCaptchaCaptchaResolver implements CaptchaResolver {

	private static final String VALIDATE_METHOD_CLASS = "com.octo.captcha.module.servlet.image.SimpleImageCaptchaServlet";

	@Override
    /**
     * <p>Valid captcha.</p>
     * @param request
     * @param token
     * @return the valid captcha
     */
	public boolean validCaptcha(ServletRequest request, CaptchaAuthenticationToken token)
			throws AuthenticationException {

		// 验证码无效
		if(StringUtils.isEmpty(token.getCaptcha())) {
			throw new IncorrectCaptchaException();
		}
		try {
			Class<?> clazz = Class.forName(VALIDATE_METHOD_CLASS);
			Object httpRequest = WebUtils.toHttp(request);
			// Try both javax and jakarta method signatures via reflection
			Method validateMethod = findValidateMethod(clazz, httpRequest);
			if (validateMethod == null) {
				throw new IncorrectCaptchaException("JCaptcha validateResponse method not found");
			}
			Boolean result = (Boolean) validateMethod.invoke(null, httpRequest, token.getCaptcha());
			return result != null && result;
		} catch (IncorrectCaptchaException e) {
			throw e;
		} catch (ClassNotFoundException e) {
			throw new IncorrectCaptchaException("JCaptcha library not found on classpath. Add jcaptcha-spring-boot-starter dependency.", e);
		} catch (Exception e) {
			throw new IncorrectCaptchaException(e);
		}
	}

	private Method findValidateMethod(Class<?> clazz, Object httpRequest) {
		// Try to find validateResponse with the actual type of httpRequest
		for (Method m : clazz.getMethods()) {
			if ("validateResponse".equals(m.getName()) && m.getParameterCount() == 2) {
				Class<?>[] paramTypes = m.getParameterTypes();
				if (paramTypes[1] == String.class && paramTypes[0].isInstance(httpRequest)) {
					return m;
				}
			}
		}
		return null;
	}

}
