package org.apache.shiro.spring.boot.captcha;

import java.util.Date;

import javax.servlet.ServletRequest;

import org.apache.commons.lang3.StringUtils;
import org.apache.shiro.authc.AuthenticationException;
import org.apache.shiro.biz.authc.exception.IncorrectCaptchaException;
import org.apache.shiro.biz.authc.exception.InvalidCaptchaException;
import org.apache.shiro.biz.authc.token.CaptchaAuthenticationToken;
import org.apache.shiro.biz.utils.SubjectUtils;
import org.apache.shiro.biz.web.filter.authc.captcha.CaptchaResolver;
import org.apache.shiro.session.Session;
import org.apache.shiro.spring.boot.ShiroBizProperties;

/**
 * A {@link CaptchaResolver} implementation that validates captchas
 * generated by the Kaptcha library, storing captcha text and creation time in the Shiro session.
 *
 * @author <a href="https://github.com/loong10k">Loong Wan</a>
 * @since 1.0.0
 */
public class ShiroKaptchaSessionResolver implements CaptchaResolver {

	/**
	 * Name of the session attribute that holds the Captcha name. Only used
	 * internally by this implementation.
	 */
	public static final String CAPTCHA_SESSION_ATTRIBUTE_NAME = ShiroKaptchaSessionResolver.class.getName() + ".Captcha";
	public static final String CAPTCHA_DATE_SESSION_ATTRIBUTE_NAME = ShiroKaptchaSessionResolver.class.getName() + ".Captcha_DATE";

	/** The session attribute key for storing the captcha text. */
	private String captchaStoreKey = CAPTCHA_SESSION_ATTRIBUTE_NAME;
	/** The session attribute key for storing the captcha creation time. */
	private String captchaDateStoreKey = CAPTCHA_SESSION_ATTRIBUTE_NAME;
	/** The captcha validity period in milliseconds, default is 60000 (60 seconds). */
	private long captchaTimeout = ShiroBizProperties.DEFAULT_CAPTCHA_TIMEOUT;

	public void init(String captchaStoreKey, String captchaDateStoreKey, long captchaTimeout) {
		if(StringUtils.isNoneEmpty(captchaStoreKey)) {
			this.captchaStoreKey = captchaStoreKey;
		}
		if(StringUtils.isNoneEmpty(captchaDateStoreKey)) {
			this.captchaDateStoreKey = captchaDateStoreKey;
		}
		if(captchaTimeout > 0) {
			this.captchaTimeout = captchaTimeout;
		}
	}

	/**
	 * Validates the captcha from a Shiro authentication token against the session-stored captcha.
	 *
	 * @param request the servlet request
	 * @param token the captcha authentication token
	 * @return true if the captcha is valid
	 * @throws AuthenticationException if the captcha is incorrect or expired
	 */
	@Override
	public boolean validCaptcha(ServletRequest request, CaptchaAuthenticationToken token)
			throws AuthenticationException {
		// 验证码无效
		if(StringUtils.isEmpty(token.getCaptcha())) {
			throw new IncorrectCaptchaException();
		}
		try {
			Session session = SubjectUtils.getSubject().getSession(true);

			// 历史验证码无效
			String sessionCapText = (String) session.getAttribute(getCaptchaStoreKey());
			if(StringUtils.isEmpty(sessionCapText)) {
				throw new IncorrectCaptchaException();
			}
			// 检查验证码是否过期
			Date sessionCapDate = (Date) session.getAttribute(getCaptchaDateStoreKey());
			if(new Date().getTime() - sessionCapDate.getTime()  > getCaptchaTimeout()) {
				throw new InvalidCaptchaException();
			}

			return StringUtils.equalsIgnoreCase(sessionCapText, token.getCaptcha());
		} catch (IncorrectCaptchaException | InvalidCaptchaException e) {
			throw e;
		} catch (Exception e) {
			throw new IncorrectCaptchaException(e);
		}
	}

	/**
	 * Stores the captcha text and creation time in the Shiro session.
	 *
	 * @param capText the captcha text to store
	 * @param capDate the captcha creation date
	 */
	public void setCaptcha(String capText, Date capDate) {
		Session session = SubjectUtils.getSubject().getSession(true);

		// store the text in the session
		session.setAttribute( getCaptchaStoreKey(), (StringUtils.isNotEmpty(capText) ? capText : null));

		// store the date in the session so that it can be compared
		// against to make sure someone hasn't taken too long to enter
		// their kaptcha
		session.setAttribute( getCaptchaDateStoreKey(), (capDate != null ? capDate : new Date()));
	}

	public String getCaptchaStoreKey() {
		return captchaStoreKey;
	}

	public String getCaptchaDateStoreKey() {
		return captchaDateStoreKey;
	}

	public long getCaptchaTimeout() {
		return captchaTimeout;
	}

}
